# Generated by Django 5.1.4 on 2025-01-08 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        help_text="введите место для выполнения привычки",
                        max_length=255,
                        verbose_name="место выполнения",
                    ),
                ),
                (
                    "time",
                    models.TimeField(help_text="введите время выполнения привычки", verbose_name="время выполнения"),
                ),
                ("action", models.TextField(help_text="введите действие привычки", verbose_name="действие привычки")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="укажите признак приятной привычки",
                        verbose_name="признак приятной привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="введите вознаграждение за выполнение привычки",
                        max_length=255,
                        null=True,
                        verbose_name="вознаграждение",
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=1,
                        help_text="введите периодичность выполнения привычки в днях (по умолчанию 1)",
                        verbose_name="периодичность выполнения",
                    ),
                ),
                (
                    "time_to_complete",
                    models.IntegerField(
                        default=120, help_text="введите время на выполнение", verbose_name="время на выполнение"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="введите признак публичности", verbose_name="признак публичность"
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="связанная привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": ("привычка",),
                "verbose_name_plural": "привычки",
            },
        ),
    ]
